export enum ControlType {
  INPUT = "INPUT",
  NUMBER = "NUMBER",
  PHONE = "PHONE",
  AUTOCOMPLETE = "AUTOCOMPLETE",
  CHECKBOX = "CHECKBOX",
  MULTISELECT = "MULTISELECT",
  MULTICHIP = "MULTICHIP",
  DATEPICKER = "DATEPICKER",
  PASSWORD = "PASSWORD",
  TEXTAREA = "TEXTAREA",
  RADIOBUTTON = "RADIONBUTTON",
}
